### ISSUE TITLE
Date in the khronos.org registry page is wrong

### ISSUE THREAD

**Issue by ratchetfreak** [KhronosGroup/DataFormat#2]
https://www.khronos.org/registry/dataformat/

> The current version is 1.1, February 16, 2015.

this should be 

> The current version is 1.1, February 16, 2016.

**Comment by oddhack** [comment]
Thanks. I fixed this and it will propagate to the website shortly.

**Comment by fluppeteer** [comment]
Yes, we spotted this just before release, but didn't get it incorporated in time!

Note that the data format spec is about to get a minor update for a typo fix, so this corrected date will in fact still not be correct. A corrected correction will follow shortly, which is why I'd not submitted this fix myself.
